package gateway

import (
	"fmt"
	"log"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Traefik dynamic config types
type TraefikDynamic struct {
	HTTP TraefikHTTP `yaml:"http"`
}

type TraefikHTTP struct {
	Routers  map[string]TraefikRouter  `yaml:"routers"`
	Services map[string]TraefikService `yaml:"services"`
}

type TraefikRouter struct {
	Rule        string     `yaml:"rule"`
	Service     string     `yaml:"service"`
	EntryPoints []string   `yaml:"entryPoints"`
	TLS        *TraefikTLS `yaml:"tls,omitempty"`
}

type TraefikTLS struct {
	CertResolver string `yaml:"certResolver"`
}

type TraefikService struct {
	LoadBalancer TraefikLB `yaml:"loadBalancer"`
}

type TraefikLB struct {
	Servers []TraefikServer `yaml:"servers"`
}

type TraefikServer struct {
	URL string `yaml:"url"`
}

// GenerateTraefikConfig writes the Traefik dynamic config file
func GenerateTraefikConfig(dir string, connections []ConnectionConfig) error {
	cfg := TraefikDynamic{
		HTTP: TraefikHTTP{
			Routers: make(map[string]TraefikRouter),
			Services: map[string]TraefikService{
				"mcp-gateway": {
					LoadBalancer: TraefikLB{
						Servers: []TraefikServer{{URL: "http://mcp-gateway:8080"}},
					},
				},
			},
		},
	}

	for _, conn := range connections {
		if !conn.Enabled {
			continue
		}
		routerName := fmt.Sprintf("mcp-%s", conn.Slug)
		cfg.HTTP.Routers[routerName] = TraefikRouter{
			Rule:        fmt.Sprintf("Host(`%s`)", conn.Domain),
			Service:     "mcp-gateway",
			EntryPoints: []string{"websecure"},
			TLS:         &TraefikTLS{CertResolver: "letsencrypt"},
		}
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal traefik config: %w", err)
	}

	// Write with header comment
	header := "# Auto-generated by mcp-gateway on config sync — DO NOT EDIT\n\n"
	content := header + string(data)

	path := filepath.Join(dir, "mcp-connections.yml")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create traefik dir: %w", err)
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("write traefik config: %w", err)
	}

	log.Printf("[traefik] wrote dynamic config: %d routers", len(cfg.HTTP.Routers))
	return nil
}
